image: golang:latest

variables:
  HIST_EVENTS_BINARY_FILE: historical-events

stages:
  - lint
  - test
  - build
  - deploy

lint:
  image: golangci/golangci-lint:latest
  stage: lint
  allow_failure: false
  script:
    - cd ./historical-events
    - golangci-lint run -v

test:
  stage: test
  script:
    - cd ./historical-events
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)
    - go test -race $(go list ./... | grep -v /vendor/)

build:
  stage: build
  script:
    - |
      go build -v -o ./historical-events/cmd/hist-events  \
      -ldflags="-X 'github.com/aliaksandrrachko/historian/historical-events/internal/build.version=$APP_VERSION' \
          -X 'github.com/aliaksandrrachko/historian/historical-events/internal/build.gitCommit=$GIT_COMMIT_HASH' \
          -X 'github.com/aliaksandrrachko/historian/historical-events/internal/build.gitAuthor=$GIT_COMMIT_AUTHOR' \
          -X 'github.com/aliaksandrrachko/historian/historical-events/internal/build.time=$(date)'" \
      ./historical-events/cmd/main.go
  artifacts:
    paths:
      - ./historical-events/cmd/hist-events

deploy:
  stage: deploy
  script: echo "Define your deployment script!"
  environment: development
  only: 
    - master