image: golang:latest

variables:
  HIST_EVENTS_BASE_DIR: $CI_PROJECT_DIR/historical-events
  HIST_EVENTS_EXECUTABLE: $HIST_EVENTS_BASE_DIR/cmd/historical-events

stages:
  - lint
  - test
  - build
  - image
  - deploy

go_lint:
  image: golangci/golangci-lint:latest
  stage: lint
  allow_failure: false
  script:
    - cd $HIST_EVENTS_BASE_DIR
    - golangci-lint run -v

helm_lint:
  stage: lint
  image: centosadmin/kubernetes-helm:3.6.3
  environment:
    name: development
  script:
    - cd $HIST_EVENTS_BASE_DIR
    - helm lint .helm/historical-events-backend
        --set image.repository=$CI_REGISTRY_IMAGE
        --set image.tag=$CI_COMMIT_REF_SLUG.$CI_PIPELINE_ID
  # only:
  #   - master


test:
  stage: test
  script:
    - cd $HIST_EVENTS_BASE_DIR
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)
    - go test -race $(go list ./... | grep -v /vendor/)

build:
  stage: build
  variables: 
    CGO_ENABLED: 0
    GOOS: linux
  script:
    - cd $HIST_EVENTS_BASE_DIR
    - |
      go build -v -o $HIST_EVENTS_EXECUTABLE  \
      -ldflags="-X 'github.com/aliaksandrrachko/historian/historical-events/internal/build.version=$CI_COMMIT_TAG' \
          -X 'github.com/aliaksandrrachko/historian/historical-events/internal/build.gitCommit=$CI_COMMIT_SHA' \
          -X 'github.com/aliaksandrrachko/historian/historical-events/internal/build.gitAuthor=$CI_COMMIT_AUTHOR' \
          -X 'github.com/aliaksandrrachko/historian/historical-events/internal/build.time=$(date)'" \
      $HIST_EVENTS_EXECUTABLE.go
  artifacts:
    paths:
      - $HIST_EVENTS_EXECUTABLE

build_image:
  stage: image
  image:
    name: gcr.io/kaniko-project/executor:debug-v1.3.0
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - |
      /kaniko/executor --context $HIST_EVENTS_BASE_DIR \
      --cache=true --cache-repo=$CI_REGISTRY_IMAGE \
      --dockerfile $HIST_EVENTS_BASE_DIR/DockerfilePreBuild \
      --destination ${CI_REGISTRY_IMAGE}:$CI_COMMIT_REF_SLUG.$CI_PIPELINE_ID

deploy:
  stage: deploy
  script: echo "Define your deployment script!"
  environment: development
  only: 
    - master