image: golang:latest

stages:
  - lint
  - test
  - deploy

lint:
  image: golangci/golangci-lint:latest
  stage: lint
  allow_failure: false
  script:
    - cd ./historical-events
    - golangci-lint run -v

test:
  stage: test
  script:
    - cd ./historical-events
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)
    - go test -race $(go list ./... | grep -v /vendor/)

compile:
  stage: build
  script:
    - echo "Warn! build"\

deploy:
  stage: deploy
  script: echo "Define your deployment script!"
  environment: development
  only: master