image: golang:latest

variables:
  BINARY_OUTPUT_FILE: __bin__/$CI_PROJECT_NAME

stages:
  - lint
  - test
  - build
  - deploy

lint:
  image: golangci/golangci-lint:latest
  stage: lint
  allow_failure: false
  script:
    - cd ./historical-events
    - golangci-lint run -v

test:
  stage: test
  script:
    - cd ./historical-events
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)
    - go test -race $(go list ./... | grep -v /vendor/)

build:
  stage: build
  script:
    - cd ./historical-events
    - mkdir -p $BINARY_OUTPUT_FILE
    - |
      go build -v -o $BINARY_OUTPUT_FILE  \
      -ldflags="-X 'github.com/aliaksandrrachko/historian/historical-events/internal/build.version=$APP_VERSION' \
          -X 'github.com/aliaksandrrachko/historian/historical-events/internal/build.gitCommit=$GIT_COMMIT_HASH' \
          -X 'github.com/aliaksandrrachko/historian/historical-events/internal/build.gitAuthor=$GIT_COMMIT_AUTHOR' \
          -X 'github.com/aliaksandrrachko/historian/historical-events/internal/build.time=$(date)'" \
      ./cmd/
  artifacts:
    paths:
      - $BINARY_OUTPUT_FILE

deploy:
  stage: deploy
  script: echo "Define your deployment script!"
  environment: development
  only: 
    - master