image: golang:latest

variables:
  HIST_EVENTS_BASE_DIR: $CI_PROJECT_DIR/historical-events
  HIST_EVENTS_EXECUTABLE: $HIST_EVENTS_BASE_DIR/cmd/historical-events

stages:
  - lint
  - test
  - build
  - deploy

lint:
  image: golangci/golangci-lint:latest
  stage: lint
  allow_failure: false
  script:
    - cd $HIST_EVENTS_BASE_DIR
    - golangci-lint run -v

test:
  stage: test
  script:
    - cd $HIST_EVENTS_BASE_DIR
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)
    - go test -race $(go list ./... | grep -v /vendor/)

build:
  stage: build
  variables: 
    - CGO_ENABLED: 0
    - GOOS: linux
  script:
    - cd $HIST_EVENTS_BASE_DIR
    - |
      go build -v -o $HIST_EVENTS_EXECUTABLE  \
      -ldflags="-X 'github.com/aliaksandrrachko/historian/historical-events/internal/build.version=$CI_COMMIT_TAG' \
          -X 'github.com/aliaksandrrachko/historian/historical-events/internal/build.gitCommit=$CI_COMMIT_SHA' \
          -X 'github.com/aliaksandrrachko/historian/historical-events/internal/build.gitAuthor=$CI_COMMIT_AUTHOR' \
          -X 'github.com/aliaksandrrachko/historian/historical-events/internal/build.time=$(date)'" \
      $HIST_EVENTS_EXECUTABLE.go
  artifacts:
    paths:
      - $HIST_EVENTS_EXECUTABLE

deploy:
  stage: deploy
  script: echo "Define your deployment script!"
  environment: development
  only: 
    - master