// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wiregen

import (
	"github.com/aliaksandrrachko/historian/historical-events/pkg/config"
	"github.com/aliaksandrrachko/historian/historical-events/pkg/ginlogrus"
	"github.com/aliaksandrrachko/historian/historical-events/pkg/health"
	"github.com/aliaksandrrachko/historian/historical-events/pkg/server"
)

// Injectors from wire.go:

func InitServer() server.HistoricalEventsServer {
	logger := ginlogrus.NewLogger()
	configConfig := config.NewRandomConfig()
	engine := server.NewEngine(logger, configConfig)
	healthCheck := health.NewDefaultHealthCheck()
	historicalEventsServer := server.NewServer(logger, configConfig, engine, healthCheck)
	return historicalEventsServer
}
