# syntax=docker/dockerfile:1

FROM golang:1.21

WORKDIR /usr/src/historical-events

COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -v -o /usr/local/bin/historical-events ./cmd/

EXPOSE 8080

CMD ["/usr/local/bin/historical-events"]